# Generated by Django 4.2.8 on 2024-01-09 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=32)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('sale_counter', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now=True)),
                ('approve', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='Course Image/')),
                ('course_file', models.FileField(upload_to='Courses/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='customer.customer')),
            ],
        ),
    ]
