# Generated by Django 4.2.8 on 2024-01-17 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 16, 15, 6, 876968)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 16, 15, 6, 876968)),
        ),
        migrations.AlterField(
            model_name='datahistory',
            name='datatime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 17, 16, 15, 6, 876968)),
        ),
    ]
