# Generated by Django 4.2.8 on 2024-01-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.IntegerField()),
                ('sale_counter', models.IntegerField(default=0)),
                ('published_date', models.DateField(auto_now=True)),
                ('approve', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='Course Image/')),
                ('course_file', models.FileField(upload_to='Courses/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='customer.customer')),
            ],
        ),
    ]
