# Generated by Django 4.2.8 on 2024-01-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='Profile/pic.png', upload_to='Profile/'),
        ),
    ]
