# Generated by Django 4.2.8 on 2024-01-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='published_date',
        ),
        migrations.AddField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
