# Generated by Django 4.2.8 on 2024-01-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_course_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approval_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
