# Generated by Django 4.2.8 on 2024-01-23 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_amounttransitionhistory_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datahistory',
            name='datatime',
        ),
        migrations.AddField(
            model_name='datahistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 16, 7, 48, 896703)),
        ),
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 16, 7, 48, 896703)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 16, 7, 48, 896703)),
        ),
    ]
