# Generated by Django 4.2.8 on 2024-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_amounttransitionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
