# Generated by Django 4.2.8 on 2024-01-23 12:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_amounttransitionhistory_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 18, 0, 55, 70363)),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursebuyhistories', to='customer.course'),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 18, 0, 55, 70363)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 18, 0, 55, 54749)),
        ),
        migrations.CreateModel(
            name='saleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 1, 23, 18, 0, 55, 70363))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesalehistories', to='customer.course')),
                ('saller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salehistories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
