# Generated by Django 4.2.8 on 2024-01-24 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_rename_saller_salehistory_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffer',
            name='remaining_amount',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 15, 54, 59, 224522)),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 15, 54, 59, 224522)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 15, 54, 59, 224522)),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 15, 54, 59, 224522)),
        ),
    ]
