# Generated by Django 4.2.8 on 2024-01-25 06:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_rename_category_name_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salehistory',
            name='seller',
        ),
        migrations.AddField(
            model_name='buyhistory',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salehistories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salehistory',
            name='sellerdfsd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salsfsehistories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 31, 20, 926295)),
        ),
        migrations.AlterField(
            model_name='buyhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 31, 20, 926295)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 31, 20, 926295)),
        ),
        migrations.AlterField(
            model_name='salehistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 31, 20, 926295)),
        ),
    ]
