# Generated by Django 4.2.8 on 2024-01-25 06:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_remove_salehistory_seller_buyhistory_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 41, 56, 974627))),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyhistories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='salehistory',
            name='course',
        ),
        migrations.RemoveField(
            model_name='salehistory',
            name='sellerdfsd',
        ),
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 41, 56, 974627)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 11, 41, 56, 974627)),
        ),
        migrations.DeleteModel(
            name='BuyHistory',
        ),
        migrations.DeleteModel(
            name='saleHistory',
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursebuyhistories', to='customer.course'),
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salehistories', to=settings.AUTH_USER_MODEL),
        ),
    ]
