# Generated by Django 4.2.8 on 2024-01-31 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_coursehistory_remove_salehistory_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_saller',
            new_name='is_seller',
        ),
        migrations.AlterField(
            model_name='amounttransitionhistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 12, 59, 32, 492665)),
        ),
        migrations.AlterField(
            model_name='course',
            name='published_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 12, 59, 32, 492665)),
        ),
        migrations.AlterField(
            model_name='coursehistory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 12, 59, 32, 492665)),
        ),
    ]
